version: '2'
services:
  graphql:
    command: npm start
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app/src:/app/src
      - ./package.json:/app/package.json
